/home/tobias/work/SunStudioProjects/saruman/src/cuda-functions.cu File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <unistd.h>
#include <string.h>
#include <argtable2.h>
#include <pthread.h>
#include <cuda.h>
#include <cutil.h>
#include `util.h`
#include `saruman.h`
#include `hash.h`
Defines
#define SWAP_CHAR(x, y) {char c; c = x; x = y; y = c;}
#define NR_OF_BLOCKS 5
Functions
__device__ void reverse_sequence (char *sequence, int sequence_length)
__device__ short int minimize (short int a, short int b, short int c)
__device__ void get_alignment (int match, int mismatch, char *read_sequences, char *genome_sequences, char *read_alignments, char *genome_alignments, short int *edit_matrices_on_device_gpu, int max_position, int edit_matrix_start, int read_sequence_length, int read_start, int genome_start, int genome_sequence_length, int error, int end_offset, int start_offset, int threadID)
__global__ void compute_score (int match, int mismatch, char *read_sequences, char *genome_sequences, int *read_offsets, int *genome_offsets, char *read_alignments, char *genome_alignments, int sample_size, short int *edit_matrices_on_device_gpu, int *edit_offsets, int *device_score_array, char *direction_array, int error)
void cuda_needleman_wunsch (int match, int mismatch, char *genome_sequences_on_host, char *read_sequences_on_host, int *genome_offsets, int *read_offsets, int *edit_offsets, int sample_size, int *read_id_array, int *genome_pos_array, char *direction_array, int error, size_t total_genome_sequence_array_size, size_t total_read_sequence_array_size, size_t total_edit_matrix_size, int do_reverse)
unsigned long get_cuda_infos (void)
Variables
float alignment_time [2]
Define Documentation
#define NR_OF_BLOCKS 5
Referenced by cuda_needleman_wunsch().
#define SWAP_CHAR(x, y) {char c; c = x; x = y; y = c;}
Swaps the chars x and y.
Referenced by reverse(), and reverse_sequence().
Function Documentation
__global__ void compute_score (int match, int mismatch, char * read_sequences, char * genome_sequences, int * read_offsets, int * genome_offsets, char * read_alignments, char * genome_alignments, int sample_size, short int * edit_matrices_on_device_gpu, int * edit_offsets, int * device_score_array, char * direction_array, int error)
References get_alignment(), and minimize().
void cuda_needleman_wunsch (int match, int mismatch, char * genome_sequences_on_host, char * read_sequences_on_host, int * genome_offsets, int * read_offsets, int * edit_offsets, int sample_size, int * read_id_array, int * genome_pos_array, char * direction_array, int error, size_t total_genome_array_size, size_t total_read_sequence_array_size, size_t total_edit_matrix_size, int do_reverse)
Wrapper functions which allows to call the CUDA implemented Smith-Waterman algorithm from other C files.
Parameters:
match costs for a match
mismatch costs for a mismatch
genome_sequences_on_host array of genome sequences
read_sequences_on_host array of read sequences
genome_offsets stop positions of each genome sequence in the genome array
read_offsets stop positions of each read sequence in the read array
edit_offsets stop positions of each edit matrix in the edit matrix array
genome_pos_array start positions per read in the reference genome
direction_array holds the direction and matching qgram(s) of each hit
error allowed error
total_genome_array_size total size of the genome array
total_read_sequence_array_size total size of the read array *
total_edit_matrix_size total size of the edit matrix array
do_reverse forward or reverse direction
read_id_array hods the id of each read in the set
sample_size size of the sample arrays
References alignment_time, be_verbose_value, forward_output_control, read_name_hash::name, NR_OF_BLOCKS, read_names, and reverse_output_control.
Referenced by prepare_cuda_alignments().
__device__ void get_alignment (int match, int mismatch, char * read_sequences, char * genome_sequences, char * read_alignments, char * genome_alignments, short int * edit_matrices_on_device_gpu, int max_position, int edit_matrix_start, int read_sequence_length, int read_start, int genome_start, int genome_sequence_length, int error, int end_offset, int start_offset, int threadID)
References reverse_sequence().
Referenced by compute_score().
unsigned long get_cuda_infos (void)
Reverses a given char array
Returns: amount of available CUDA memory in bytes
__device__ short int minimize (short int a, short int b, short int c)
Referenced by compute_score().
__device__ void reverse_sequence (char * sequence, int sequence_length)
References SWAP_CHAR.
Referenced by get_alignment().
Variable Documentation
float alignment_time[2]
Referenced by cuda_needleman_wunsch(), and main().