/home/tobias/work/SunStudioProjects/saruman/src/hash.h File Reference
#include `util.h`
#include <uthash.h>
Data Structures
struct qgram_hash
a structure needed to built a hash index of qgram start positions
struct result_hash
a structure needed to built a hash index of mapped reads
Functions
unsigned short int add_qgram_to_index (char *qgram, int start_position_paramater)
unsigned short int add_start_position (unsigned int read_id, int start_position, char direction_and_qgrams, struct result_hash **results, unsigned int *alignment_queue, int possible)
short int perform_hashtable_identity_check (void)
struct qgram_hash * qgram_lookup (char *qgram)
void * qgram_to_read_mapping (void *threadarg)
void print_qgram_index_statistics (int qgram_size)
struct result_hash * run_seashore (int chunksize, int run, int number_of_start_positions, int qgram_length, int error, int rest, int do_reverse, unsigned int *data_array, struct result_hash *results, unsigned int *alignment_queue, unsigned int *data_array_offsets)
void prepare_cuda_alignments (int mismatch, int match, int error, struct result_hash *results, unsigned int *alignment_queue, int do_reverse)
void cuda_queue_check (int mismatch, int match, int error, struct result_hash *results, unsigned int *alignment_queue, int do_reverse)
void clear_result_hash (struct result_hash *results)
void clear_name_hash (void)
void clear_qgram_index (void)
Variables
int chunk_value
int sw_match_value
int sw_mismatch_value
int genome_chunk_run
int exact_tresh
unsigned int bases_read
char * forward_output_control
char * reverse_output_control
char * genome_sequence
unsigned short int read_length_value
unsigned short int print_non_matching_reads
char * reads
struct read_name_hash * read_names
unsigned short int maximal_errors_allowed
unsigned int pos_counter
unsigned int hash_members
Function Documentation
unsigned short int add_qgram_to_index (char * qgram, int start_position_paramater)
Checks if the given start position for the given qgram is a new one and stores it in the corresponding struct of the qgram_hash.
Parameters:
qgram the qgram
start_position_paramater start position to be added to the qgram
Returns: 0 if the qgram is new, 1 if a read is updated with a new position
References qgram_hash::next_pos, pos_counter, qgram_hash::positions, qgram_hash::qgram, and qgram_lookup().
Referenced by construct_qgram_index().
unsigned short int add_start_position (unsigned int read_id, int start_position, char direction_and_qgrams, struct result_hash ** results, unsigned int * alignment_queue, int possible)
Checks if the given start position for the given read is a new one and stores it in the corresponding struct of the result_hash.
Parameters:
read_id unique number of the read
start_position start position to be added to the read
direction_and_qgrams holds the direction and the matching qgram(s)
results reference to the result hash of this thread
alignment_queue reference to the alignment queque of this thread
Returns: 0 if the read is new, 1 if the start position already exists and 2 if a read is updated with a new position
References result_hash::direction_and_matching_qgrams, exact_tresh, maximal_errors_allowed, result_hash::next_pos, result_hash::positions, and result_hash::read_id.
Referenced by run_seashore().
void clear_name_hash (void)
Clears and frees the read_name_hash
Returns: nothing
References read_names.
Referenced by main().
void clear_qgram_index (void)
Clears and frees the qgram_hash
Returns: nothing
References qgram_hash::positions.
Referenced by main().
void clear_result_hash (struct result_hash * results)
Clears and frees the result_hash
Parameters:
results reference to the hash to be cleared
Returns: nothing
References result_hash::direction_and_matching_qgrams, and result_hash::positions.
Referenced by qgram_to_read_mapping().
void cuda_queue_check (int mismatch, int match, int error, struct result_hash * results, unsigned int * alignment_queue, int do_reverse)
Checks the number of alignments in queue and launches prepare_cuda_alignments if the chunksize is reached
Parameters:
mismatch the mismatch costs
match the match costs
error maximal allowed error
results the result hash for the correspondig thread
alignment_queue holds the number of alignments in queue
do_reverse determines the direction of this run
Returns: nothing
References chunk_value, and prepare_cuda_alignments().
Referenced by run_seashore().
short int perform_hashtable_identity_check (void)
Performs an self check of the qgram_hash i.e. iterate over the hash and check each key for existence
Returns: 0 if check is passed, 1 otherwise
References qgram_hash::hh, qgram_hash::qgram, and qgram_lookup().
void prepare_cuda_alignments (int mismatch, int match, int error, struct result_hash * results, unsigned int * alignment_queue, int do_reverse)
Prepares and collects all necessary data for the CUDA alignment phase.
Parameters:
mismatch the mismatch costs
match the match costs
error maximal allowed error
results the result hash for the correspondig thread
alignment_queue holds the number of alignments in queue
do_reverse determines the direction of this run
Returns: nothing
References bases_read, chunk_value, cuda_needleman_wunsch(), result_hash::direction_and_matching_qgrams, genome_chunk_run, genome_chunk_value, genome_sequence, result_hash::hh, result_hash::next_pos, result_hash::positions, result_hash::read_id, read_length_value, reads, and reverse_complement().
Referenced by cuda_queue_check(), and qgram_to_read_mapping().
void print_qgram_index_statistics (int qgram_size)
Prints some statistics about the qgram_hash
Parameters:
qgram_size size of the used qgram
Returns: nothing
References hash_members, and pos_counter.
Referenced by main().
struct qgram_hash* qgram_lookup (char * qgram) [read]
Performs a lookup in the qgram hash table.
Parameters:
qgram qgram to look up
Returns: a pointer to the struct if found, NULL pointer else.
Referenced by add_qgram_to_index(), perform_hashtable_identity_check(), and qgram_to_read_mapping().
void* qgram_to_read_mapping (void * threadarg)
Tries to assign all needed qgrams for mapping to a each read
Parameters:
threadarg a struct holding all necessary information for the mapping and alignment phase
Returns: nothing
< holds the number of alignments in queue to be aligned
References thread_data::chunksize, clear_result_hash(), thread_data::do_reverse, thread_data::error, qgram_hash::next_pos, thread_data::number_of_start_positions, qgram_hash::positions, prepare_cuda_alignments(), thread_data::qgram_length, qgram_length, qgram_lookup(), thread_data::qgram_start_positions, thread_data::read_array, thread_data::read_number, thread_data::readlength, thread_data::rest, results, reverse_complement(), run_seashore(), sw_match_value, and sw_mismatch_value.
Referenced by main().
struct result_hash* run_seashore (int chunksize, int run, int number_of_start_positions, int qgram_length, int error, int rest, int do_reverse, unsigned int * data_array, struct result_hash * results, unsigned int * alignment_queue, unsigned int * data_array_offsets) [read]
Starts the SEASHORE mapping algorithm
Parameters:
chunksize number of reads to process in one run
run number of the actual run
number_of_start_positions number of qgram start positions per read
qgram_length length of one qgram
error maximal allowed error
rest rest of the read after beeing cut into X qgrams
do_reverse determines the direction of this run
data_array array holding the qgram to read mapping
results the result hash for the correspondig thread
alignment_queue holds the number of alignments in queue
data_array_offsets start positions for each qgram's start positions
Returns: nothing
References add_start_position(), cuda_queue_check(), exact_tresh, forward_output_control, genome_chunk_run, genome_chunk_value, genome_sequence, read_name_hash::name, print_non_matching_reads, result_hash::read_id, read_length_value, read_names, reads, reverse_complement(), reverse_output_control, sw_match_value, and sw_mismatch_value.
Referenced by qgram_to_read_mapping().
Variable Documentation
unsigned int bases_read
Referenced by main(), and prepare_cuda_alignments().
int chunk_value
holds the number of reads to be processed in one run
Referenced by check_user_input(), cuda_queue_check(), main(), and prepare_cuda_alignments().
int exact_tresh
Referenced by add_start_position(), main(), and run_seashore().
char* forward_output_control
Referenced by cuda_needleman_wunsch(), main(), and run_seashore().
int genome_chunk_run
Referenced by main(), prepare_cuda_alignments(), and run_seashore().
char* genome_sequence
Referenced by main(), prepare_cuda_alignments(), and run_seashore().
unsigned int hash_members
number of reads in the result array aka mapped reads
Referenced by main(), and print_qgram_index_statistics().
unsigned short int maximal_errors_allowed
Referenced by add_start_position(), main(), and read_multiple_fasta_file().
unsigned int pos_counter
counts number of start qgram start postions
Referenced by add_qgram_to_index(), main(), and print_qgram_index_statistics().
unsigned short int print_non_matching_reads
print non matching reads
Referenced by check_user_input(), main(), and run_seashore().
unsigned short int read_length_value
holds the length of each read in bp
Referenced by check_user_input(), main(), prepare_cuda_alignments(), and run_seashore().
struct read_name_hash* read_names
holds the results aka start positions in genome
char* reads
Referenced by main(), prepare_cuda_alignments(), and run_seashore().
char* reverse_output_control
Referenced by cuda_needleman_wunsch(), main(), and run_seashore().
int sw_match_value
holds the costs for a match used by the CUDA Smith-Waterman module
Referenced by check_user_input(), main(), qgram_to_read_mapping(), and run_seashore().
int sw_mismatch_value
holds the costs for a match used by the CUDA Smith-Waterman module
Referenced by check_user_input(), main(), qgram_to_read_mapping(), and run_seashore().