/home/tobias/work/SunStudioProjects/saruman/src/saruman.c File Reference
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <pthread.h>
#include <time.h>
#include `hash.h`
#include `argtable2.h`
#include `util.h`
#include `saruman.h`
#include `cuda-functions.h`
Defines
#define NUM_THREADS 3
Functions
int main (int argc, char *argv[])
Variables
struct thread_data thread_data_array [NUM_THREADS]
Define Documentation
#define NUM_THREADS 3
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
Main function. Starts the program and does some housekeeping before calling the mapping functions
Parameters:
argc number of CLI arguments
argv char array of the CLI arguments
References alignment_time, bases_read, check_user_input(), chunk_value, thread_data::chunksize, clear_name_hash(), clear_qgram_index(), construct_qgram_index(), thread_data::do_reverse, thread_data::error, error_rate_value, exact_tresh, forward_output_control, genome_chunk_run, genome_chunk_value, genome_file_value, genome_sequence, hash_members, line_offset, maximal_errors_allowed, read_name_hash::name, NUM_THREADS, thread_data::number_of_start_positions, pos_counter, print_non_matching_reads, print_qgram_index_statistics(), thread_data::qgram_length, qgram_length, thread_data::qgram_start_positions, qgram_to_read_mapping(), thread_data::read_array, read_file_value, read_length_value, read_multiple_fasta_file(), read_names, thread_data::read_number, read_number_value, thread_data::readlength, reads, thread_data::rest, reverse_output_control, sw_match_value, sw_mismatch_value, and thread_data_array.
Variable Documentation
struct thread_data thread_data_array[NUM_THREADS]
Referenced by main().