/home/tobias/work/SunStudioProjects/saruman/src/util.c File Reference
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include `argtable2.h`
#include `util.h`
#include `saruman.h`
#include `hash.h`
Defines
#define VERSION `SVN-BUILD-M2`
#define SWAP_CHAR(x, y) {char c; c = x; x = y; y = c;}
Functions
void reverse (char *sequence, int sequence_length)
void reverse_complement (char *sequence, int sequence_length)
signed short int check_user_input (int argc, char *argv[])
char * read_multiple_fasta_file (const char *filename, int max_entries, int readlength)
void construct_qgram_index (char *genome_sequence, int qgram_size, int run)
Define Documentation
#define SWAP_CHAR(x, y) {char c; c = x; x = y; y = c;}
#define VERSION `SVN-BUILD-M2`
Referenced by check_user_input().
Function Documentation
signed short int check_user_input (int argc, char * argv[])
Checks the user input. Tests if all mandatory values are given.
Parameters:
argc number of CLI arguments
argv char array of the CLI arguments
Returns: 0 program starrted but directly terminated (show help, version etc)
 -1 missing mandaroty value
 2 all mandatory values ok, start mapping programm
References be_verbose_parameter, be_verbose_value, chunk_parameter, chunk_value, end, error_rate_parameter, error_rate_value, fastq_parameter, genome_chunk_parameter, genome_chunk_value, genome_file_parameter, genome_file_value, help_parameter, print_non_matching_reads, print_non_matching_reads_parameter, read_file_parameter, read_file_value, read_length_parameter, read_length_value, read_number_parameter, read_number_value, sw_match_parameter, sw_match_value, sw_mismatch_parameter, sw_mismatch_value, use_fastq, VERSION, and version_parameter.
Referenced by main().
void construct_qgram_index (char * genome_sequence, int qgram_size, int run)
Constructs the main qgram index (qgram_hash) holding all start positions for each qgram in the genome
Parameters:
genome_sequence the genome sequence returned by read_genome_fasta_file
qgram_size the desired qgram size (computed automaticly as short int qgram_length = ceil(read_length / (maximal_errors_allowed+1))-1)
Returns: nothing
References add_qgram_to_index(), and genome_chunk_value.
Referenced by main().
char* read_multiple_fasta_file (const char * filename, int max_entries, int readlength)
Reads and parses the given read file.
Parameters:
filename path to the file to read
max_entries number of reads to parse
readlength length of the reads
Returns: a char array containing all reads in order
< holds the results aka start positions in genome
References line_offset, MAX_READ_DESCRIPTION_LENGTH, maximal_errors_allowed, read_name_hash::name, read_names, read_name_hash::read_number, and use_fastq.
Referenced by main().
void reverse (char * sequence, int sequence_length)
Reverses a given string
Parameters:
sequence char sequence
sequence_length length of the sequence to be reversed
Returns: a char array containing the genome
References SWAP_CHAR.
Referenced by reverse_complement().
void reverse_complement (char * sequence, int sequence_length)
References reverse().
Referenced by prepare_cuda_alignments(), qgram_to_read_mapping(), and run_seashore().